ALTER TABLE users ADD COLUMN IF NOT EXISTS balance_brl DECIMAL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
UPDATE users SET balance_brl = 10000.00, updated_at = NOW() WHERE id = '1ad0a835-46a4-465a-a436-6275c9dcdde1';
