export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // User
  NEEDS_CPF: "NEEDS_CPF",
  INVALID_CPF: "INVALID_CPF",

  // Wallet
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  LIMIT_REACHED: "LIMIT_REACHED",

  // Payment
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",

  // Inventory
  PENDING_INVENTORY_NOT_FOUND: "PENDING_INVENTORY_NOT_FOUND",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  CARD_NOT_OWNED: "CARD_NOT_OWNED",

  // Market
  LISTING_NOT_FOUND: "LISTING_NOT_FOUND",
  CANNOT_BUY_OWN_LISTING: "CANNOT_BUY_OWN_LISTING",
  LISTING_NOT_ACTIVE: "LISTING_NOT_ACTIVE",

  // Generic
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  FORBIDDEN: "FORBIDDEN",
} as const;
